{% set version = '0.3-7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ecdat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Ecdat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Ecdat/Ecdat_{{ version }}.tar.gz
  sha256: 7baece35076c341954d9f2a3f084892dca92b93f45f743b003a1dfa7a4f64a47

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ecfun
  run:
    - r-base
    - r-ecfun

test:
  commands:
    - $R -e "library('Ecdat')"           # [not win]
    - "\"%R%\" -e \"library('Ecdat')\""  # [win]

about:
  home: https://www.r-project.org
  license: GPL-2
  summary: Data sets for econometrics, including political science.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ryankn
# Package: Ecdat
# Version: 0.3-7
# Date: 2020-02-10
# Title: Data Sets for Econometrics
# Author: Yves Croissant <yves.croissant@let.ish-lyon.cnrs.fr> and Spencer Graves
# Maintainer: Spencer Graves <spencer.graves@effectivedefense.org>
# Depends: R (>= 3.5.0), Ecfun
# Suggests:
# Description: Data sets for econometrics, including political science.
# LazyData: true
# License: GPL (>= 2)
# URL: https://www.r-project.org
# NeedsCompilation: no
# Packaged: 2020-02-10 15:03:08 UTC; sbgraves
# Repository: CRAN
# Date/Publication: 2020-02-10 16:10:03 UTC
